# Generated by Django 3.0.7 on 2020-06-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_cityview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityView',
        ),
    ]
